const AuthActionTypes = {
    GOOGLE_SIGN_IN_START: 'auth/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'auth/EMAIL_SIGN_IN_START',
    DEFAULT_SIGN_IN_START: 'auth/DEFAULT_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'auth/SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'auth/SIGN_IN_FAILURE',
    CHECK_USER_SESSION: 'auth/CHECK_USER_SESSION',
    SIGN_OUT_START: 'auth/SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'auth/SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'auth/SIGN_OUT_FAILURE',
    SIGN_UP_START: 'auth/SIGN_UP_START',
    SIGN_UP_SUCCESS: 'auth/SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'auth/SIGN_UP_FAILURE'
}

export default AuthActionTypes
