const CanvasActionTypes = {
    FOUND: 'FOUND',
    FETCH_CANVAS_FRAMES: 'FETCH_CANVAS_FRAMES',
    ADD_NEW_FRAME: 'ADD_NEW_FRAME',
    TOGGLE_FRAME_NODE_VIEW: 'TOGGLE_FRAME_NODE_VIEW',
    TOGGLE_FRAME_CHECK: 'TOGGLE_FRAME_CHECK'
}

export default CanvasActionTypes
