const CanvasActionTypes = {
    FETCH_CANVAS_FRAMES: 'FETCH_CANVAS_FRAMES',
    ADD_NEW_FRAME: 'ADD_NEW_FRAME',
    TOGGLE_NODE_COLLAPSE: 'TOGGLE_NODE_COLLAPSE',
    TOGGLE_NODE_CHECK_ONE: 'TOGGLE_NODE_CHECK_ONE',
    TOGGLE_NODE_CHECK_CASCADE: 'TOGGLE_NODE_CHECK_CASCADE'
}

export default CanvasActionTypes
