const WorkspaceActionTypes = {
    FETCH_WORKSPACE_START: 'FETCH_WORKSPACE_START',
    FETCH_WORKSPACE_SUCCESS: 'FETCH_WORKSPACE_SUCCESS',
    FETCH_WORKSPACE_FAILURE: 'FETCH_WORKSPACE_FAILURE',
    CREATE_WORKSPACE: 'CREATE_NEW_WORKSPACE',
    SELECT_WORKSPACE: 'SELECT_WORKSPACE',
    DELETE_WORKSPACE: 'DELETE_WORKSPACE',
    UPDATE_WORKSPACE: 'UPDATE_WORKSPACE'
}

export default WorkspaceActionTypes
