const NodeActionTypes = {
    FETCH_START: 'node/FETCH_START',
    FETCH_SUCCESS: 'node/FETCH_SUCCESS',
    FETCH_FAILURE: 'node/FETCH_FAILURE',
    APPEND_TO_PARENT_NODE: 'node/APPEND_TO_PARENT_NODE',
    APPEND_CHILD_NODE: 'node/APPEND_CHILD_NODE',
    APPEND_SIBLING_NODE: 'node/APPEND_SIBLING_NODE',
    SET_ACTIVE_GROUP: 'node/SET_ACTIVE_GROUP',
    TOGGLE_NODE_COLLAPSE: 'node/TOGGLE_NODE_COLLAPSE',
    TOGGLE_NODE_CHECK_ONE: 'node/TOGGLE_NODE_CHECK_ONE',
    TOGGLE_NODE_CHECK_CASCADE: 'node/TOGGLE_NODE_CHECK_CASCADE',
    DRAG_CHILD_NODE: 'node/DRAG_CHILD_NODE'
}

export default NodeActionTypes
