const frameActionTypes = {
    FETCH_FRAMES_START: 'FETCH_FRAMES_START',
    FETCH_FRAMES_SUCCESS: 'FETCH_FRAMES_SUCCESS',
    FETCH_FRAMES_FAILURE: 'FETCH_FRAMES_FAILURE',
    ADD_NEW_FRAME: 'ADD_NEW_FRAME',
    TOGGLE_NODE_COLLAPSE: 'TOGGLE_NODE_COLLAPSE',
    TOGGLE_NODE_CHECK_ONE: 'TOGGLE_NODE_CHECK_ONE',
    TOGGLE_NODE_CHECK_CASCADE: 'TOGGLE_NODE_CHECK_CASCADE'
}

export default frameActionTypes
